### ISSUE TITLE
thumbs not loading/showing[solved]

### ISSUE THREAD

**Issue by irshad2809** [The-LoneWolf/AndroPress#3]
W/System.err: org.json.JSONException: No value for thumbnail
W/System.err:     at org.json.JSONObject.get(JSONObject.java:389)
W/System.err:     at org.json.JSONObject.getString(JSONObject.java:550)
W/System.err:     at ir.technopedia.wordpressjsonclient.model.PostModel.fromJson(PostModel.java:50)
W/System.err:     at ir.technopedia.wordpressjsonclient.fragment.PostFragment$4.onSuccess(PostFragment.java:174)
W/System.err:     at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:152)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:148)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5461)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
i am getting this for every post response 
**but i have set featured images for posts **

**Comment by The-LoneWolf** [comment]
have you tested the demo app? send me your api address please to check for details

**Comment by irshad2809** [comment]
http://www.khedmart.com/api/ 
this is my api address

**Comment by The-LoneWolf** [comment]
in your blog api returns this because you may have customized your posts  :) i will send code edits needed in next answer
 `"attachments":[

    {
        "id":8110,
        "url":"http://www.khedmart.com/wp-content/uploads/2017/02/1-2.jpg",
        "slug":"1-7",
        "title":"1",
        "description":"",
        "caption":"",
        "parent":8109,
        "mime_type":"image/jpeg",
        "images":{
            "medium_large":{
                "url":"http://www.khedmart.com/wp-content/uploads/2017/02/1-2.jpg",
                "width":320,
                "height":308
            }
        }
    }

],`

**Comment by The-LoneWolf** [comment]
in class PostModel you shoud change fromJson method with this

`
public void fromJson(JSONObject jsonObject) {
        try {
            id = jsonObject.getInt("id");
            url = jsonObject.getString("url");
            title = jsonObject.getString("title");
            status = jsonObject.getString("status");
            content = jsonObject.getString("content");
            date = jsonObject.getString("date");
            for (int i = 0; i < jsonObject.getJSONArray("categories").length(); i++) {
                categories.add(jsonObject.getJSONArray("categories").getJSONObject(i).getString("title"));
            }
            author = jsonObject.getJSONObject("author").getString("nickname");
            for (int i = 0; i < jsonObject.getJSONArray("comments").length(); i++) {
                CommentModel commentModel = new CommentModel();
                commentModel.fromJson(jsonObject.getJSONArray("comments").getJSONObject(i));
                comments.add(commentModel);
            }
            comment_count = jsonObject.getInt("comment_count");
            comment_status = jsonObject.getString("comment_status");
            img = "";
            for (int i = 0; i < jsonObject.getJSONArray("attachments").length(); i++) {
            if(jsonObject.getJSONArray("attachments").getJSONObject(i).getString("mime_type").Contains("image")){
                        img = jsonObject.getJSONArray("attachments").getJSONObject(i).getString("url");
                        break;
                }
            }
        } catch (JSONException e) {
            e.printStackTrace();
        }
}
`

**Comment by irshad2809** [comment]
thanks for support .it worked after making some (2 to be exact )changes to above code.

`public void fromJson(JSONObject jsonObject) { try { id = jsonObject.getInt("id"); url = jsonObject.getString("url"); title = jsonObject.getString("title"); status = jsonObject.getString("status"); content = jsonObject.getString("content"); date = jsonObject.getString("date"); for (int i = 0; i < jsonObject.getJSONArray("categories").length(); i++) { categories.add(jsonObject.getJSONArray("categories").getJSONObject(i).getString("title")); } author = jsonObject.getJSONObject("author").getString("nickname"); for (int i = 0; i < jsonObject.getJSONArray("comments").length(); i++) { CommentModel commentModel = new CommentModel(); commentModel.fromJson(jsonObject.getJSONArray("comments").getJSONObject(i)); comments.add(commentModel); } comment_count = jsonObject.getInt("comment_count"); comment_status = jsonObject.getString("comment_status");

-  **//img = ""; not needed** 
for (int i = 0; i < jsonObject.getJSONArray("attachments").length(); i++) { if(jsonObject.getJSONArray("attachments").getJSONObject(i).getString("mime_type").contains("image")){ img = jsonObject.getJSONArray("attachments").getJSONObject(i).getString("url"); break; } } } catch (JSONException e) { e.printStackTrace(); } }`

Contains != contains

**Comment by irshad2809** [comment]
you are right my blog has many customizations ,and too many changes are needed for fitting those in this app , ill try myself .  thanks for greate project

**Comment by irshad2809** [comment]
1. 

hey sorry if bothering , so my client is not using featured images for posts but they are giving images inside the content , is it possible to show the first image in content as thumbnail OR if this is too much , how can i show static/ predefined thumbs(different for each cat ) for every categories. 

2.
and Push Notification Added With FCM(FireBase Cloud Messaging)
how it works ?,automatic push or i have to do it manually

**Comment by The-LoneWolf** [comment]
1. you should use jsoup library to take first photo out of content.
for categories you should customize the json api plugin
2. it is manuall you should send it from firebase console
