### ISSUE TITLE
Support URL with HTTPS?[solved]

### ISSUE THREAD

**Issue by abuhenasobuj** [The-LoneWolf/AndroPress#4]
Is there any possibility support `https` link?

**Comment by The-LoneWolf** [comment]
i have used asynchttp by loopj as networking library as examples show on loopj site it supports https in links. please test it and let me now the result :)

**Comment by abuhenasobuj** [comment]
I tired with https site but unfortunately it's not working. Something need to be change/adjustment? Here is logcat [AndroPress - Problem with HTTPS (Secure Sockets Layer) URL.](https://gist.github.com/abuhenasobuj/9111ae58a5b6e9e7fe6e0ea27dbfa6b8)

**Comment by The-LoneWolf** [comment]
try replacing this with what i have used in NetUtils.java
`asyncClient = new AsyncHttpClient(true, 80, 443);`

if you don't get it work try using this
http://stackoverflow.com/questions/26633349/disable-ssl-as-a-protocol-in-httpsurlconnection
create class NoSSLv3Factory 
and then add 
`HttpsURLConnection.setDefaultSSLSocketFactory(new NoSSLv3Factory());`
in NetUtils.java in the app before 
` private static AsyncHttpClient client = new AsyncHttpClient();`

netutils.java https://github.com/The-LoneWolf/AndroPress/blob/master/app/src/main/java/ir/technopedia/wordpressjsonclient/util/NetUtil.java

there is also a solution given here give it a try as well
https://github.com/loopj/android-async-http/issues/746
