### ISSUE TITLE
what time will be update?

### ISSUE THREAD

**Issue by skating507** [The-LoneWolf/AndroPress#5]
this souce what time will be update?

**Comment by The-LoneWolf** [comment]
hi
is there any problem with source?

**Comment by skating507** [comment]
just want to have more feature.
e.g
1 Add Transition Effects
2 Add Settings
3 Add Different Views

**Comment by The-LoneWolf** [comment]
ah :)) of course i will update it soon. i was busy. but there will be an update soon

**Comment by skating507** [comment]
good news
