### ISSUE TITLE
Load data from last wordpress

### ISSUE THREAD

**Issue by misapi** [The-LoneWolf/AndroPress#6]
Hello, the application can not retrieve the data from the new version of wordpress with JSON-API plugin,
Do you have a Solution Please?

**Comment by The-LoneWolf** [comment]
Hi
It was better to say that you could'nt get app to work cause i updated my test wordpress installation and JSON-API plugin and the old app is still working :D 

please explain what did you do? and provide your wordpress address so i can check if you have the right configuration

**Comment by misapi** [comment]
Thanks;
my adress isi www.misapi.unaux.com/api/

**Comment by The-LoneWolf** [comment]
the api is allright. what's wrong with your app? do you get error? if yes send me the logcat please

**Comment by misapi** [comment]
Sorry, I dont have any error in my Code

**Comment by misapi** [comment]
I have just this error at the opening project file in Android Studio.



23:56	Gradle sync started

23:56	Error Loading Project: Cannot load 3 modules Details...

23:57	Gradle sync failed: Minimum supported Gradle version is 3.3. Current version is 3.2. If using the gradle wrapper, try editing the distributionUrl in D:\ProjetAPK\TEST\AndroPress\gradle\wrapper\gradle-wrapper.properties to gradle-3.3-all.zip
			Consult IDE log for more details (Help | Show Log)


![capture](https://user-images.githubusercontent.com/20212147/28442243-ae5638ee-6daf-11e7-8237-5f48019b74c4.PNG)

**Comment by The-LoneWolf** [comment]
update the projects gradle version and compile it
